### ISSUE TITLE
Raiders spawn 10 feet away from a horde of ghouls

### ISSUE THREAD

**Issue by kooarbiter** [Digdugxx/bad-deathclaw#95]
Removing the ghouls from the ruins right beside the raider spawn (which most raiders accidentally bump into while taking shit from the spawn area, of which there are like 6 at any given time, most of them being glowing or armored) and if it's supposed to be a high level area, move the camp that raiders spawn in to a not high level area, since they spawn with pipes and single shotguns and shit armor and almost never work together to kill them from the onset since someone running from the ghouls often gets killed right at the spawn causing all other raiders to die upon spawning before they can even get their bearings

**Comment by AndrewL97** [comment]
This codebase is no longer being updated, please see https://github.com/BadDeathclaw/TG-Claw
