### ISSUE TITLE
Stages for deconstruction of "store walls" have missing textures.

### ISSUE THREAD

**Issue by Ctr-Truescreen** [Digdugxx/bad-deathclaw#96]
Upon cutting the outer grille of a store wall (the ones in the mall or used in the NCR base), i couldn't go any further due to the wall showing up as transparent (no texture) and couldn't click or alt-click it.

**Comment by AndrewL97** [comment]
This codebase is no longer being updated, please see https://github.com/BadDeathclaw/TG-Claw
