### ISSUE TITLE
Pipe rifles and pipe pistols cannot be reloaded with 10mm ammo boxes.

### ISSUE THREAD

**Issue by Ctr-Truescreen** [Digdugxx/bad-deathclaw#97]
Upon firing and removing a _Pipe Rifle_/_Pipe Pistol_'s round, the weapon refuses to accept rounds from a _10mm Ammo Box_ or singular rounds, making the weapon unable to be reloaded.

**Comment by AndrewL97** [comment]
This codebase is no longer being updated, please see https://github.com/BadDeathclaw/TG-Claw
